SELECT 
    TC.CONSTRAINT_NAME,
    TC.TABLE_NAME,
    TCC.COLUMN_NAME,
    TC.CONSTRAINT_TYPE
FROM
    INFORMATION_SCHEMA.TABLE_CONSTRAINTS TC
    JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE TCC ON TC.CONSTRAINT_NAME = TCC.CONSTRAINT_NAME
WHERE
    TC.TABLE_NAME = 'USERS'
    AND TC.CONSTRAINT_TYPE = 'UNIQUE';